fastlane_version "2.1.1"

before_all do
  cocoapods
end

desc "Runs all the tests"
lane :test do
  scan(scheme: "Realm Browser")
end

desc "Build the new realease for MAS and GitHub, submit build to ITC and upload dSYM files to HockeyApp"
lane :build do |options|
  releaseDir = "release"
  versionNumber = get_version_number
  gitHubArchiveName = "RealmBrowser-#{versionNumber}.zip"
  dSymArhiveName = "Realm Browser.app.dSYM.zip"

  # build an archive and export dSYM files
  gym(
    scheme: "Realm Browser",
    clean: true,
    output_directory: releaseDir,
    buildlog_path: releaseDir,
  )

  # export pkg for ITC
  xcexport({export_options_plist: {method: "app-store"}, export_path: releaseDir})

  # export Developer ID signed app for GitHub release
  xcexport({export_options_plist: {method: "developer-id"}, export_path: releaseDir})

  # archive the Developer ID signed app
  Dir.chdir "../#{releaseDir}" do
    zip("Realm Browser.app", gitHubArchiveName, true)
  end
  
  # delete incorrect ipa path in lane context
  Actions.lane_context[SharedValues::IPA_OUTPUT_PATH] = nil

  # fix dSYM path
  Actions.lane_context[SharedValues::DSYM_OUTPUT_PATH] = "#{releaseDir}/#{dSymArhiveName}"
  
  if options[:submit_to_hockey]
    hockey(
      api_token: ENV['HOCKEY_API_TOKEN'],
      public_identifier: ENV['HOCKEY_APP_ID'],
      ipa: "#{releaseDir}/#{gitHubArchiveName}", # should be specified to create a new version
      dsym: "#{releaseDir}/#{dSymArhiveName}",
      strategy: "replace" # this will not replace symbols but add the new ones, we don're really care about app itself anyway
    )
  end
  
  if options[:submit_to_itc]
    deliver(
      username: ENV['ITC_USERNAME'],
      app_version: "#{versionNumber}",
      pkg: "#{releaseDir}/Realm Browser.pkg",
      skip_screenshots: true,
      skip_metadata: true
    )
  end
  
  Dir.chdir ".." do
    zip(releaseDir, releaseDir, true)
  end
end

def zip(source_path, output_path, remove_source_path)
  sh("zip --symlinks -r \"#{output_path}.zip\" \"#{source_path}\"")

  if remove_source_path
    sh("rm -rf \"#{source_path}\"")
  end
end
